Repository 3drepo/3drepo.io, pull requests merged in 2020-09, with the labels that each got.

#2191 Issue 2106 Azure Devops pipeline support
  .azure/Docker/Dockerfile
  .azure/Docker/src/init.sh
  .azure/build-and-deploy.yaml
  .azure/build.yaml
  .azure/deploy.yaml
Labels: enhancement

#2206 ISSUE #2205
  .azure/build-and-deploy.yaml
Labels: config update, hotfix

#2221 ISSUE #2218 fix error 500 if viewpoint is set to null on issue creation
  backend/models/ticket.js
Labels: hotfix

#2219 ISSUE #2217 - Changed the logic for waiting to be ready in tree sagas
  frontend/modules/tree/tree.sagas.ts
Labels: hotfix
